name: hotel-booking-local

services:
  postgres:
    image: postgres:17-alpine
    container_name: hotel-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - hotel-network

  redis:
    image: redis:8.10.0-alpine
    container_name: hotel-redis

    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}"
      ]

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - hotel-network


volumes:
  postgres_data:
  redis_data:


networks:
  hotel-network:
    driver: bridge